# Generated by Django 5.0.6 on 2024-07-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceo',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ceo',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ceo',
            old_name='Title',
            new_name='title',
        ),
    ]
