# Generated by Django 5.0.6 on 2024-07-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('logo1', models.ImageField(upload_to='uploads/')),
                ('logo2', models.ImageField(upload_to='uploads/')),
                ('side_image', models.ImageField(upload_to='uploads/')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
