# Generated by Django 5.0.6 on 2024-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='logo1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='logo2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
