# Generated by Django 5.0.6 on 2024-07-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_logo1_alter_about_logo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='side_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
